### ISSUE TITLE
Should keep track of 'type' = 'private' in CloudinaryField

### ISSUE THREAD

**Issue by r4vi** [cloudinary/pycloudinary#18]
It'd be useful if the CloudinaryField kept track of 'type' as if this isn't tracked then the build_url function creates incorrect urls for files uploaded with 'type':'private'

**Comment by oppianmatt** [comment]
Why was this closed? It wasn't fixed. I just raised the same issue and it still exists:

https://github.com/cloudinary/pycloudinary/issues/44

The issue is that the field does not keep track of the type. We can upload with type=private but then we can't use it unless we remember the type somewhere (but that's why we have a database).
