### ISSUE TITLE
TypeError: expected string or bytes-like object, when removing an image in Django's UpdateView

### ISSUE THREAD

**Issue by sunnyville** [cloudinary/pycloudinary#98]
Hello,

I'm using Cloudinary in my Django application, and everything is working fine. Except in my UpdateVIew, when a user checks 'clear' to remove an uploaded image and submit the form this error is shown:

> TypeError: expected string or bytes-like object

The error page in the browser also shows these highlighted messages:

> ...\lib\site-packages\cloudinary\models.py in to_python
>             return self.parse_cloudinary_resource(value) ...

> ...\lib\site-packages\cloudinary\models.py in parse_cloudinary_resource
>         m = re.match(CLOUDINARY_FIELD_DB_RE, value) ...

> ...\AppData\Local\Programs\Python\Python36-32\lib\re.py in match
>     return _compile(pattern, flags).match(string) 

These are what my model, view and form look like:

models.py:
```
class Item(models.Model):
    name = models.CharField(max_length=255)
    image1 = CloudinaryField('image', blank=True, null=True)
```
views.py
```
class ItemUpdateView(LoginRequiredMixin, UpdateView):
    model = models.Item
    form_class = forms.ItemForm
```
forms.py
```
class ItemForm(forms.ModelForm):
    image1 = CloudinaryFileField(
                required=False,
                options = {'crop': 'limit', 'width': 546, 'height': 1000,})
    class Meta:
        model = models.Item
        fields = ("image1", "name")
```
I think Cloudinary is still expecting something when the field's value is empty. I've used `required=False` because I want the image to be optional as that is how it is in my model. I have looked at the docs and searched the web and I just can't figure out how to fix this.

Thanks.

**Comment by tocker** [comment]
The error indicates that the value passed to `to_python` is not a string.

We may be missing a check for "self":

```
if isinstance(value, CloudinaryField):
            return value
```

Can you please debug and check the type and value of the `value` argument passed to `to_python`?

**Comment by twoblokeswithapostie** [comment]
I'm hitting this issue. The value sent is Boolean False and match expects a string, so it fails. 

The exception is thrown in this line:

return _compile(pattern, flags).match(string) 

These are the variable values:


flags | 0
pattern | '(?:(?P<resource_type>image\|raw\|video)/(?P<type>upload\|private\|authenticated)/)?(?:v(?P<version>\\d+)/)?(?P<public_id>.*?)(\\.(?P<format>[^.]+))?$'
string | False

This happens when you click on "Clear" checkbox inside a Django's ModelForm. It's a default widget for deleting a FileField value. 

Here's a full traceback:

Traceback:

File "/Users/mariogudelj/Envs/cp/lib/python2.7/site-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/Users/mariogudelj/Envs/cp/lib/python2.7/site-packages/django/core/handlers/base.py" in _legacy_get_response
  249.             response = self._get_response(request)

File "/Users/mariogudelj/Envs/cp/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/Users/mariogudelj/Envs/cp/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/Users/mariogudelj/Envs/cp/lib/python2.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  23.                 return view_func(request, *args, **kwargs)

File "/Users/mariogudelj/projects/cp/console/views.py" in console_views_wrapper
  91.         return function(*args, **kwargs)

File "/Users/mariogudelj/projects/cp/console/views.py" in order_edit
  1012.         if product_edit_form.is_valid() and quote_edit_form.is_valid():

File "/Users/mariogudelj/Envs/cp/lib/python2.7/site-packages/django/forms/forms.py" in is_valid
  183.         return self.is_bound and not self.errors

File "/Users/mariogudelj/Envs/cp/lib/python2.7/site-packages/django/forms/forms.py" in errors
  175.             self.full_clean()

File "/Users/mariogudelj/Envs/cp/lib/python2.7/site-packages/django/forms/forms.py" in full_clean
  386.         self._post_clean()

File "/Users/mariogudelj/Envs/cp/lib/python2.7/site-packages/django/forms/models.py" in _post_clean
  413.             self.instance.full_clean(exclude=exclude, validate_unique=False)

File "/Users/mariogudelj/Envs/cp/lib/python2.7/site-packages/django/db/models/base.py" in full_clean
  1227.             self.clean_fields(exclude=exclude)

File "/Users/mariogudelj/Envs/cp/lib/python2.7/site-packages/django/db/models/base.py" in clean_fields
  1269.                 setattr(self, f.attname, f.clean(raw_value, self))

File "/Users/mariogudelj/Envs/cp/lib/python2.7/site-packages/django/db/models/fields/__init__.py" in clean
  605.         value = self.to_python(value)

File "/Users/mariogudelj/Envs/cp/lib/python2.7/site-packages/cloudinary/models.py" in to_python
  74.             return self.parse_cloudinary_resource(value)

File "/Users/mariogudelj/Envs/cp/lib/python2.7/site-packages/cloudinary/models.py" in parse_cloudinary_resource
  50.         m = re.match(CLOUDINARY_FIELD_DB_RE, value)

File "/Users/mariogudelj/Envs/cp/lib/python2.7/re.py" in match
  141.     return _compile(pattern, flags).match(string)

Exception Type: TypeError at /console/order-edit/2525308/
Exception Value: expected string or buffer

**Comment by twoblokeswithapostie** [comment]
Can I bump this issue? I'm not sure how to fix it, but I think that to_python method inside CloudinaryField needs to be patched to return value if the type is boolean. Cheers, m

**Comment by macarena** [comment]
Any solution?

**Comment by macarena** [comment]
I've fixed it changing to_python method.
The value passed em deleting de image is False, not None. So I just added this possibility on the method.

` 
def to_python(self, value):
        if isinstance(value, CloudinaryResource):
            return value
        elif isinstance(value, UploadedFile):
            return value
        elif value is None or value is False:
            return value
        else:
            return self.parse_cloudinary_resource(value)
`

**Comment by tocker** [comment]
@macarena that the image is kept in Cloudinary shouldn't be a problem, yet you can always remove it manually or as part of the application process.
From a simple test I did your suggested solution works (or at least doesn't break...)
If this is a viable solution I'll modify the code.

@sunnyville @twoblokeswithapostie Comments are welcome!

**Comment by twoblokeswithapostie** [comment]
@macarena nailed it. That is the solution indeed.

**Comment by jakhax** [comment]
@tocker @macarena can please explain how I can fix this issue am new to django and this is causing issues to a profile edit form in my app or atleast how i can remove the check button

**Comment by jakhax** [comment]
@macarena solution works very well indeed, @tocker please consider fixing this issue.

**Comment by yakirp** [comment]
Hey @macarena,
It's on our roadmap, we will update.

Thanks,
--Yakir

**Comment by goodtune** [comment]
As a workaround, I've implemented the following on my form.

```python
class UserPhotoForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("photo",)

    def clean_photo(self):
        data = self.cleaned_data.get("photo")
        if data is False:
            data = None
        return data
```

**Comment by Dpython2017** [comment]
I remove the migrations folder and then python manage.py makemigrations app_name. It worked for me
